version: '2'
services: 
  zookeeper:
    network_mode: host
    image: jplock/zookeeper 
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      ZK_CONFIG: tickTime=2000,initLimit=10,syncLimit=5,maxClientCnxns=128,forceSync=no,clientPort=2181
      ZK_ID: 1
  mesos-master:
    image: garland/mesosphere-docker-mesos-master 
    network_mode: host
    ports:
      - "5050:5050"
    environment:
      LIBPROCESS_IP: ${HOST_IP}
  mesos-master:
    image: garland/mesosphere-docker-mesos-master 
    network_mode: "host"
    ports:
      - "5050:5050"
    environment:
      MESOS_HOSTNAME: ${HOST_IP}
      MESOS_ZK: zk://${HOST_IP}:2181/mesos
      MESOS_PORT: 5050
      MESOS_LOG_DIR: /var/log/mesos
      MESOS_QUORUM: 1
      MESOS_REGISTRY: in_memory
      MESOS_WORK_DIR: /var/lib/mesos
    depends_on:
      - zookeeper
  marathon:
    image: garland/mesosphere-docker-marathon
    ports:
      - "8080:8080"
    command: --master zk://${HOST_IP}:2181/mesos --zk zk://${HOST_IP}:2181/marathon
    depends_on:
      - mesos-master
  mesos-slave-1:
    image: bbenns/mesos-slave-with-docker:latest 
    entrypoint: mesos-slave
    network_mode: host
    pid: host
    ports: 
      - "5051:5051"
    environment: 
      MESOS_CONTAINERIZERS: docker,mesos     
      MESOS_RESOURCES: ports(*):[11000-11999]
      MESOS_MASTER: zk://${HOST_IP}:2181/mesos
      MESOS_HOSTNAME: ${HOST_IP}
      LIBPROCESS_IP: ${HOST_IP}
      MESOS_PORT: 5051 
      MESOS_LOGGING_LEVEL: INFO
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/run/docker.sock   
    depends_on:
      - mesos-master
    image: garland/mesosphere-docker-mesos-master:latest
    entrypoint: mesos-slave
    environment: 
      MESOS_MASTER: zk://${HOST_IP}:2181/mesos
      MESOS_LOG_DIR: /var/log/mesos
      MESOS_LOGGING_LEVEL: INFO
    depends_on:
      - marathon

